CREATE TABLE IF NOT EXISTS course (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(80) NOT NULL,
  number VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS ta_users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE note
(id SERIAL PRIMARY KEY NOT NULL,
course_id INT NOT NULL REFERENCES course(id),
user_id INT NOT NULL REFERENCES ta_users(id),
content TEXT NOT NULL,
date DATE NOT NULL
);